### ISSUE TITLE
v0.9.8 does not compile on M2 due to something with libklusolvex.dylib 

### ISSUE THREAD

**Issue by NLaws** [dss-extensions/OpenDSSDirect.jl#103]
since upgrading to v0.9.8 from v0.9.7 OpenDSSDirect.jl fails to build with the following error:
```sh
ERROR: LoadError: InitError: could not load library "/Users/nlaws/.julia/packages/OpenDSSDirect/TOPxW/deps/apple/libklusolvex.dylib"
dlopen(/Users/nlaws/.julia/packages/OpenDSSDirect/TOPxW/deps/apple/libklusolvex.dylib, 0x0001): tried: '/Users/nlaws/.julia/packages/OpenDSSDirect/TOPxW/deps/apple/libklusolvex.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/nlaws/.julia/packages/OpenDSSDirect/TOPxW/deps/apple/libklusolvex.dylib' (no such file), '/Users/nlaws/.julia/packages/OpenDSSDirect/TOPxW/deps/apple/libklusolvex.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Comment by PMeira** [comment]
> (have 'arm64', need 'x86_64')

Are you using the x86-64 Julia on purpose? A while ago, somebody had a similar issue with MATLAB, and they had accidentally installed the Intel version.

I could only reproduce the error message if I first use a native Julia (ARM), followed by a x86-64 Julia. That caused Julia to mix the binaries, maybe due to the precompilation cache being built with ARM as a target.  
If I rename/delete my `~/.julia`, it works fine. There's probably a simpler fix, but I personally don't mix archs.

**Comment by NLaws** [comment]
> Are you using the x86-64 Julia on purpose? 

Nope, not sure how I fat-fingered that one 🤦
