### ISSUE TITLE
Bus voltage problem

### ISSUE THREAD

**Issue by Fbinot** [dss-extensions/OpenDSSDirect.jl#68]
[Julia_code.zip](https://github.com/dss-extensions/OpenDSSDirect.jl/files/5831650/Julia_code.zip)

Hello,
I am a new user of OpenDSS with Julia. I previously use with Matlab.
 I develop a small network Network000.dss. This network is managed by a DSS file Network_master.dss. When I run it on OpenDSS, the network is solved and I get the voltage profile.

I develop a similar code main_julia.jl in Julia. This code should give me bus voltage but I only receive zero for all the LV bus. 
I tested main_julia.jl with Master.dss of 8500bus network and I receive good values (non-zero voltages). I tested my 
code in Vscode and Juno with same results. 

![Juno_display](https://user-images.githubusercontent.com/45371579/104947492-20908d00-59bc-11eb-8e91-bfec773fc516.png)

All the data are available in the Zip folder Julia_code.zip. I don't understand what I am doing wrong.
Regards,
Fbinot

**Comment by PMeira** [comment]
> This network is managed by a DSS file Network_master.dss. When I run it on OpenDSS, the network is solved and I get the voltage profile.

Since it still returned zeros for me in the OpenDSS GUI, the issue became clear: I use 60 Hz as default base frequency, which is the default from OpenDSS. You probably changed it to 50 Hz previously, which the GUI will use as default until it's reset to 60.

For OpenDSSDirect.jl (and DSS Extensions in general), we don't use the registry settings, being multi-platform and not a GUI application -- when using multiple instances/processes, the registry/file behavior would be ill-defined.

Please check https://github.com/dss-extensions/dss_capi/blob/master/docs/known_differences.md for some other important differences and notes.

To fix this, just set the default frequency before creating the circuit, something like:

```
clear
set defaultbasefrequency=50
new Circuit.RefCircuit phases=3 bus1=Node_00000.1.2.3 basekv=20.00 pu=1 angle=0.00 r0=0.7 r1=0.8 x0=3.9 x1=4.3
// ...
```

We recommend always adding the base frequency explicitly in the .DSS scripts, even if you use the official Windows version of OpenDSS. It's a common mistake to run a system rated for 60 Hz with a default 50 Hz, getting unexpected results.

Also note the circuit itself already includes a source, you probably don't need that extra one, and you should add the source voltages to the bases: `Set voltagebases=[20, 0.4]`. I recommend looking into some smaller examples like the IEEE4 test cases and the "Default Circuit" section from the OpenDSS Manual.

**Comment by PMeira** [comment]
> I am a new user of OpenDSS with Julia. I previously use with Matlab.

@Fbinot Oh, and if you want to test your previous code that uses OpenDSS in MATLAB before migrating to Julia, you can try [DSS_MATLAB](https://github.com/dss-extensions/dss_matlab/). DSS_MATLAB uses the same OpenDSS engine used in OpenDSSDirect.jl, so you can expect it to work the same besides the API organization (and interface performance; MATLAB is slowish).

**Comment by PMeira** [comment]
I tweaked the README to add some more links and info. 
I assume we can close the issue, feel free to reopen it if I missed anything.
