### ISSUE TITLE
Use of DSS.Lib.ActionCodes 

### ISSUE THREAD

**Issue by asavasci** [dss-extensions/OpenDSSDirect.jl#74]
I am getting the error when using action codes like `DSS.SwtControls.Action(DSS.Lib.ActionCodes_Open)`,  as `ActionCodes_Open::ActionCodes = 0x00000001` but the function accepts only integer numbers.

**Comment by PMeira** [comment]
@asavasci Please update to v0.7.3. Just released and addresses that and a few other minor issues.

`Idx` was exposed for a lot of classes in this release. The `Idx()` getter for SwtControls is still missing since there was a bug in DSS C-API (setter works fine), so it will be exposed in the upcoming v0.8.0 after https://github.com/dss-extensions/OpenDSSDirect.jl/pull/73 is merged.

Most of the other enums/flags seem fine, so it was just a coincidence that the handling for SwtControls was missing.

**Comment by PMeira** [comment]
Closing since v0.8.0 was released with the `Idx` fix. A bunch of other missing stuff implemented in DSS C-API will be exposed in #84
