### ISSUE TITLE
Changing Vsource in OpenDSSDirect.jl

### ISSUE THREAD

**Issue by Leila-2550** [dss-extensions/OpenDSSDirect.jl#91]
I am running power flow in OpenDSSDirect. jl and at some stage in my code, I need to change the substation setpoint voltage, Vsource, in my code. Here is the piece of code that I use to update Vsource, but it is not working, still my Vsource value remains = 1 per unit. Any help is appreciated. Thank you.

for i=1:10 # i is time
if i>=3
_ODSS.Vsources.AllNames()
_ODSS.Vsources.Name("source")
_ODSS.Vsources.PU(1.2)
else
_ODSS.Vsources.AllNames()
_ODSS.Vsources.Name("source")
_ODSS.Vsources.PU(1.0)
end
V_source =_ODSS.Vsources.PU()
[@show](https://sourceforge.net/u/show/) V_source
end

**Comment by PMeira** [comment]
Hi, @Leila-2550, for general questions prefer to post on https://github.com/orgs/dss-extensions/discussions for more visibility ("Q&A" or "General" sections should be fine).

First, note that you could use loadshapes (e.g. Daily property in the Vsource) to control the voltage magnitude. Search for "Vsource object" in https://dss-extensions.org/dss_properties.html for the list of properties. This would enable easier time-series simulations coupled with other components in non-snapshot modes.

From you snippet, it seems fine. Maybe the issue is in other part of your code. 

On `_ODSS.Vsources.AllNames()`: You don't need `AllNames()`, especially in the loop -- you're not even using its output here. Grabbing a list of all names outside the loop to get the list of Vsource objects could make sense, though.

I prepared the sample below with some comments too and it works as expected for me:

```julia
using OpenDSSDirect

# Load a circuit somehow -- for conciseness we create a one-load circuit head.
dss("""
    clear
    new circuit.test_circuit bus1=1 BasekV=10
    new load.test_load phases=3 bus1=1 kV=10 kW=1000
    set mode=snapshot
""")

# Display the list of sources available
@show Vsources.AllNames()

# Activate the target source:
# You can either use the name...
Vsources.Name("source")
# Or the index of the object like
# Vsources.Idx(1)

# And activate the load too. 
# This will also activate it as the current circuit element, be careful when
# manipulating multiple elements and using different interfaces!
Loads.Name("test_load")

for i=1:10
    if i >= 3
        # Note that if you only have one Vsource and left it active out of the loop,
        # you don't need to reactivate it here. When in doubt, it's fine to reactivate.
        Vsources.PU(1.2)
    else
        Vsources.PU(1.0)
    end
    # Since we have set the mode to snapshot, let's solve a snapshot here
    Solution.Solve()

    # Some properties are updated only after a Solve. It's not the case for Vsources.PU(),
    # but it's a good habit to avoid checking before solving.
    V_source = Vsources.PU()
    @show V_source
    # Check the load status
    @show CktElement.Name(), real(CktElement.TotalPowers())
end
```

I got this output with the latest ODD.jl version (v0.9.4):
```
Vsources.AllNames() = ["source"]
V_source = 1.0
(CktElement.Name(), real(CktElement.TotalPowers())) = ("Load.test_load", [999.9999999077229])
V_source = 1.0
(CktElement.Name(), real(CktElement.TotalPowers())) = ("Load.test_load", [999.9999999999998])
V_source = 1.2
(CktElement.Name(), real(CktElement.TotalPowers())) = ("Load.test_load", [1305.1406084523894])
V_source = 1.2
(CktElement.Name(), real(CktElement.TotalPowers())) = ("Load.test_load", [1305.215065960484])
V_source = 1.2
(CktElement.Name(), real(CktElement.TotalPowers())) = ("Load.test_load", [1305.2150659603933])
V_source = 1.2
(CktElement.Name(), real(CktElement.TotalPowers())) = ("Load.test_load", [1305.2150659603933])
V_source = 1.2
(CktElement.Name(), real(CktElement.TotalPowers())) = ("Load.test_load", [1305.2150659603933])
V_source = 1.2
(CktElement.Name(), real(CktElement.TotalPowers())) = ("Load.test_load", [1305.2150659603933])
V_source = 1.2
(CktElement.Name(), real(CktElement.TotalPowers())) = ("Load.test_load", [1305.2150659603933])
V_source = 1.2
(CktElement.Name(), real(CktElement.TotalPowers())) = ("Load.test_load", [1305.2150659603933])
```

Does this work for you?

If not, please list more details, like versions for OpenDSSDirect.jl and Julia, and OS (Windows, Linux, mac?). Feel free to post more of your code if you think that would help.

**Comment by Leila-2550** [comment]
Hi @PMeira,

Thank you for your comprehensive response. It works for me as well.

Cheers,
