### ISSUE TITLE
Any way to avoid working directory being reset at the end of a run?

### ISSUE THREAD

**Issue by Realife-Brahmin** [dss-extensions/OpenDSSDirect.jl#95]
Upon trying to run the [tutorial example](https://dss-extensions.org/OpenDSSDirect.jl/latest/) for this package, I realized that running it once changes my directory to the one containing the .dss file, making any further runs after the first one futile, if I'm not using absolute paths, but relative paths.

In this code, I'm bypassing this problem by manually saving my original directory address and `cd`-ing to it at the end of the run, but is there a simpler way to do the same?

```julia
using OpenDSSDirect

# Store the current directory to cd to later, as I don't like the package changing my directory at the end of the run
original_directory = pwd()

foldername = joinpath(".", "OpenDSSDirect", "5wwHs", "examples", "8500-Node") # Works

filename = joinpath(foldername, "Master.dss")

dss("""
    clear
    compile $(filename)
    solve
""")

function main()
    loadnumber = Loads.First()
    kWsum = 0.0
    kvarsum = 0.0
    
    while loadnumber > 0
        kWsum += Loads.kW()
        kvarsum += Loads.kvar()
        loadnumber = Loads.Next()
    end

    kWsum, kvarsum
end

result = main()

# Reset the working directory to its original state
cd(original_directory)

println(result)
```

**Comment by kdheepak** [comment]
I believe if you use `redirect $filename` instead of `compile $filename`, OpenDSS will not change the directory. Any disk operations (such as writing out the voltage) will happen in the current working directory at that point.

**Comment by PMeira** [comment]
See also [OpenDSSDirect.Basic.AllowChangeDir](
https://dss-extensions.org/OpenDSSDirect.jl/dev/api/#OpenDSSDirect.Basic.AllowChangeDir-Tuple{DSSContext,%20Bool}).

Setting `AllowChangeDir` to false will still track the directory internally, but avoid actually changing the working directory. If you plan to use multi-threading/multiple DSS engines, this is a must, otherwise the each engine will try to change the working directory of the process.

In general, using `redirect` as @kdheepak suggested is a better practice, but by default the engine will still temporarily change the working dir (without toggling `AllowChangeDir`).

**Comment by Realife-Brahmin** [comment]
> I believe if you use `redirect $filename` instead of `compile $filename`, OpenDSS will not change the directory. Any disk operations (such as writing out the voltage) will happen in the current working directory at that point.

Serves my purpose. Thank you.
